New pr [pullrequest]
tylermann/public_test pull request #16
Opened 2017-10-27 15:19 UTC by tylermann

test pr

2017-10-27 17:06 UTC, tylermann commented on test.py
> +    pass
is this doing anything?

2017-10-27 17:10 UTC, tylermann commented
test

2017-10-27 17:18 UTC, tylermann commented
test2

2017-10-27 17:19 UTC, tylermann commented
test3

2017-10-27 17:19 UTC, tylermann commented on test.py
> +    pass
doesn't look like it

2017-10-27 17:20 UTC, tylermann commented
test4

2017-10-27 17:21 UTC, tylermann commented
test5

2017-10-27 17:22 UTC, tylermann commented
test6

2017-10-30 14:59 UTC, tylermann commented
test7

2017-10-30 15:22 UTC, tylermann commented
test8

2017-10-30 15:23 UTC, tylermann commented
test9

2017-10-30 15:24 UTC, tylermann commented
test10

2017-10-30 15:26 UTC, tylermann commented
test11

2017-10-30 15:29 UTC, tylermann commented
test12

2017-10-31 13:53 UTC, pbarsallo requested changes
need some changes here

2017-10-31 13:56 UTC, tylermann commented
test13

2017-10-31 21:29 UTC, ghost reviewed
:thumbsup:

2017-10-31 21:31 UTC, ghost reviewed
:thumbsdown:

2017-11-03 17:38 UTC, ghost reviewed
test

2017-11-09 20:56 UTC, tylermann commented on test.py
> +    pass
okay

2017-11-09 20:57 UTC, tylermann commented on test.py
> +    pass
done

2017-11-09 20:59 UTC, tylermann commented on test.py
>      a += 2
two

2018-01-18 18:04 UTC, danMateer commented on test.py
> +    pass
Reply 01182018

2018-01-23 22:51 UTC, danMateer commented
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/tylermann/public_test/16)*
<!-- Sent from Reviewable.io -->

2019-12-18 20:27 UTC, closed without merging